### ISSUE TITLE
Is there a need for this tool if the oemetadata builder includes similar functionality ?

### ISSUE THREAD

**Issue by jh-RLI** [sedos-project/open_annotation_tool#2]
I think it would be nice to have a local tool to annotate the metadata. But what are the use cases? I could imagine that it would be great to have this tool to automatically edit/update existing metadata (many files).

**Comment by chrwm** [comment]
> I could imagine that it would be great to have this tool to automatically edit/update existing metadata (many files)

Yes, this could be the case until the function you described is also implemented in the oemetadata builder.

A method currently not in the oemetadata builder and specific to the oedatamodel-parameter is creating and inserting the user-column-dicts needed to fill the columns `source`, `method`, `comment`, `bandwith_type`, `version`.
The method (it does not concern the metadata) for creating the dicts is already there, and I'd like to keep it because doing this manually is time-intense and error-prone. 

Change of repo name could be possible.

**Comment by chrwm** [comment]
For ontology annotation tools see [oemetabuilder](https://openenergy-platform.org/dataedit/oemetabuilder/).
